-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 15:38:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema developers_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `developers_db` ;

-- -----------------------------------------------------
-- Schema developers_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `developers_db` DEFAULT CHARACTER SET utf8 ;
USE `developers_db` ;

-- -----------------------------------------------------
-- Table `developers_db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`customers` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`companies` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`companies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`projects` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`developers` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`developers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`skills` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `skills` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`developers_has_skills` (
  `developers_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`developers_id`, `skills_id`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_id` ASC),
  INDEX `fk_developers_has_skills_developers1_idx` (`developers_id` ASC),
  CONSTRAINT `fk_developers_has_skills_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `developers_db`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `developers_db`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`projects_has_customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`projects_has_customers` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`projects_has_customers` (
  `projects_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `customers_id`),
  INDEX `fk_projects_has_customers_customers1_idx` (`customers_id` ASC),
  INDEX `fk_projects_has_customers_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_projects_has_customers_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `developers_db`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_customers_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `developers_db`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`companies_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`companies_has_projects` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`companies_has_projects` (
  `companies_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `projects_id`),
  INDEX `fk_companies_has_projects_projects1_idx` (`projects_id` ASC),
  INDEX `fk_companies_has_projects_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `developers_db`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `developers_db`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`projects_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`projects_has_developers` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`projects_has_developers` (
  `projects_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `developers_id`),
  INDEX `fk_projects_has_developers_developers1_idx` (`developers_id` ASC),
  INDEX `fk_projects_has_developers_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `developers_db`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `developers_db`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `developers_db`.`companies_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developers_db`.`companies_has_developers` ;

CREATE TABLE IF NOT EXISTS `developers_db`.`companies_has_developers` (
  `companies_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `developers_id`),
  INDEX `fk_companies_has_developers_developers1_idx` (`developers_id` ASC),
  INDEX `fk_companies_has_developers_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_companies_has_developers_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `developers_db`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `developers_db`.`developers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
